[build]
  base = "."

[functions]
  directory = "./js"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://arweave.demobase.org"
  to = "/"
  status = 200
  force = true

[[redirects]]
    from = '/functions/*'
    to = '/.netlify/functions/:splat'
    status = 200